export const chelseaPlayers = [
	{ id: 1, player: "Sanchez R. (B)", status: "first squad" },
	{ id: 2, player: "James R.", status: "first squad" },
	{ id: 3, player: "Disasi A.", status: "first squad" },
	{ id: 4, player: "Silva T.", status: "first squad" },
	{ id: 5, player: "Cucurella M.", status: "first squad" },
	{ id: 6, player: "Calcedo M.", status: "first squad" },
	{ id: 7, player: "Fernandez E.", status: "first squad" },
	{ id: 8, player: "Palmer C.", status: "first squad" },
	{ id: 9, player: "Gallagher C.", status: "first squad" },
	{ id: 10, player: "Sterling R.", status: "first squad" },
	{ id: 11, player: "Jackson N.", status: "first squad" },
	{ id: 12, player: "Badiashile B.", status: "reserve" },
	{ id: 13, player: "Maatsen I.", status: "reserve" },
	{ id: 14, player: "Madueke N.", status: "reserve" },
	{ id: 15, player: "Matos A.", status: "reserve" },
	{ id: 16, player: "Petrovic D.", status: "reserve" },
	{ id: 17, player: "Pochettino M.", status: "dis" },
	{ id: 18, player: "Bettineli M.", status: "coach" },
	{ id: 19, player: "Chalobah T.", status: "coach" },
	{ id: 20, player: "Chilwell B.", status: "coach" },
	{ id: 21, player: "Fofana W.", status: "coach" },
	{ id: 22, player: "Lavia R.", status: "coach" },
];
export const manCityPlayers = [
	{ id: 1, player: "Ederson (B)", status: "first squad" },
	{ id: 2, player: "Walker K.", status: "first squad" },
	{ id: 3, player: "Dias R.", status: "first squad" },
	{ id: 4, player: "Akanji M.", status: "first squad" },
	{ id: 5, player: "Gvardiol J.", status: "first squad" },
	{ id: 6, player: "Calcedo M.", status: "first squad" },
	{ id: 7, player: "Rodri", status: "first squad" },
	{ id: 8, player: "Silva B.", status: "first squad" },
	{ id: 9, player: "Foden P.", status: "first squad" },
	{ id: 10, player: "Alvarez J.", status: "first squad" },
	{ id: 11, player: "Doku J.", status: "first squad" },
	{ id: 12, player: "Bobb O.", status: "reserve" },
	{ id: 13, player: "Carson S.", status: "reserve" },
	{ id: 14, player: "Lewis R.", status: "reserve" },
	{ id: 15, player: "Nunes M.", status: "reserve" },
	{ id: 16, player: "Philips K.", status: "reserve" },
	{ id: 17, player: "Ortega S.", status: "reserve" },
	{ id: 18, player: "Guardiola P.", status: "dis" },
	{ id: 19, player: "De Bruyne K.", status: "coach" },
	{ id: 20, player: "Gomez S.", status: "coach" },
	{ id: 21, player: "Stones J.", status: "coach" },
];
